version: "3.7"

services:
    etop:
        container_name: etop-merchant
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "9001:8080"

    db:
        image: mysql:latest
        container_name: database
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: etop
            MYSQL_ROOT_PASSWORD: etop2580@
            MYSQL_PASSWORD: etop2580@
            MYSQL_USER: root
        volumes:
            - dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - etop-network


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - localhost
        ports:
            - "9002:8080"                      # phpMyAdmin accessible at http://localhost:8080
        networks:
            - etop-network


volumes:
    dbdata:

networks:
    etop-network:
